# Generated by Django 5.2.12 on 2026-07-22 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_userprofile_coins_userprofile_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='word_id',
        ),
    ]
